site_name: 'Function Library & Snippets'
site_description: 'A custom functions library'
site_author: 'Win Iden'
docs_dir: docs/
repo_name: 'ciden6481/library'
repo_url: 'https://github.com/ciden6481/Library'
nav:
    - Home: index.md
    - DAX: DAX/DAX-statements.md
    - Excel: excel/excel-functions.md
    - Power BI: powerbi/pbi-functions.md
    - Power Query: powerquery/pq-functions.md
    - Misc: misc/misc.md

theme:
  name: 'material'
