site_name: 'Function Library & Snippets'
site_description: 'A custom functions library'
site_author: 'Win Iden'
site_url: 'https://ciden6481.github.io/Library/'
docs_dir: docs/
repo_name: 'ciden6481/library'
repo_url: 'https://github.com/ciden6481/Library'
nav:
    - Home: index.md
    - DAX: DAX/
    - Excel: excel/excel-functions.md
    - Power BI: powerbi/pbi-functions.md
    - Power Query: powerquery/pq-functions.md
    - Misc: misc/misc.md

theme:
  name: 'material'
  icon:
      logo: material/function-variant
  features:
      - navigation.instant
      - navigation.tracking
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.path
      - toc.follow
      - toc.integrate
      - search.suggest
      - search.highlight
      - content.code.copy
      - content.code.annotate


      
  palette: 
          # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
 
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
  - pymdownx.inlinehilite

  - pymdownx.superfences

