site_name: 'Function Library & Snippets'
site_description: 'A custom functions library'
site_author: 'Win Iden'
docs_dir: docs/
repo_name: 'winiden/library'
repo_url: 'https://github.com/winiden/Library'
nav:
    - Home: index.md
    - DAX: DAX/DAX-statements.md
    - Excel: excel/excel-functions.md
    - Power BI: pbi-functions.md
    - Power Query: pq-functions.md
    - Misc: misc/misc.md

theme:
  name: 'material'
